[project]
name = 'contracts'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.dca-simple]
path = 'contracts/dca-simple.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
